/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.IOException;
import java.net.Inet4Address;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author pc
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        nombretext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema inventario");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Tipo");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir TIPO", "Mayorista ", "Minorista Humano", "Minorista Simulado", "Cliente" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        nombretext.setToolTipText("Nombre Jugador");
        nombretext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretextActionPerformed(evt);
            }
        });
        nombretext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombretextKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Nueva Entidad");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombretext, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombretext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombretextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nombretext.getText().length() > 2) {
            if (comboTipo.getSelectedIndex() != 0) {
                try {

                    if (comboTipo.getSelectedIndex() == 1) {
                        Mayoristavista f = new Mayoristavista(nombretext.getText(), Inet4Address.getLocalHost().getHostAddress());
                        f.setVisible(true);
                        this.setVisible(false);
                    }
                    if (comboTipo.getSelectedIndex() == 2) {
                        MinoritaVista f = new MinoritaVista(nombretext.getText(), Inet4Address.getLocalHost().getHostAddress(), false);
                        f.setVisible(true);
                        this.setVisible(false);
                    }

                    if (comboTipo.getSelectedIndex() == 3) {
                        MinoritaVista f = new MinoritaVista(nombretext.getText(), Inet4Address.getLocalHost().getHostAddress(), true);
                        f.setVisible(true);
                        this.setVisible(false);
                    }
                     if (comboTipo.getSelectedIndex() == 4) {
                        ClienteVista f = new ClienteVista(nombretext.getText(), Inet4Address.getLocalHost().getHostAddress(), true);
                        f.setVisible(true);
                        this.setVisible(false);
                    }
                } catch (UnknownHostException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Elija Un Tipo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique el Nombre");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombretextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombretextKeyTyped
        if (!((evt.getKeyChar() + "").equals(" ")
                || (evt.getKeyChar() + "").equals("a")
                || (evt.getKeyChar() + "").equals("q")
                || (evt.getKeyChar() + "").equals("w")
                || (evt.getKeyChar() + "").equals("e")
                || (evt.getKeyChar() + "").equals("r")
                || (evt.getKeyChar() + "").equals("t")
                || (evt.getKeyChar() + "").equals("y")
                || (evt.getKeyChar() + "").equals("u")
                || (evt.getKeyChar() + "").equals("i")
                || (evt.getKeyChar() + "").equals("o")
                || (evt.getKeyChar() + "").equals("p")
                || (evt.getKeyChar() + "").equals("a")
                || (evt.getKeyChar() + "").equals("s")
                || (evt.getKeyChar() + "").equals("d")
                || (evt.getKeyChar() + "").equals("f")
                || (evt.getKeyChar() + "").equals("g")
                || (evt.getKeyChar() + "").equals("h")
                || (evt.getKeyChar() + "").equals("j")
                || (evt.getKeyChar() + "").equals("k")
                || (evt.getKeyChar() + "").equals("l")
                || (evt.getKeyChar() + "").equals("ñ")
                || (evt.getKeyChar() + "").equals("z")
                || (evt.getKeyChar() + "").equals("x")
                || (evt.getKeyChar() + "").equals("c")
                || (evt.getKeyChar() + "").equals("v")
                || (evt.getKeyChar() + "").equals("b")
                || (evt.getKeyChar() + "").equals("n")
                || (evt.getKeyChar() + "").equals("m")
                || (evt.getKeyChar() + "").equals(",")
                || (evt.getKeyChar() + "").equals("Q")
                || (evt.getKeyChar() + "").equals("W")
                || (evt.getKeyChar() + "").equals("E")
                || (evt.getKeyChar() + "").equals("R")
                || (evt.getKeyChar() + "").equals("T")
                || (evt.getKeyChar() + "").equals("Y")
                || (evt.getKeyChar() + "").equals("U")
                || (evt.getKeyChar() + "").equals("I")
                || (evt.getKeyChar() + "").equals("P")
                || (evt.getKeyChar() + "").equals("A")
                || (evt.getKeyChar() + "").equals("S")
                || (evt.getKeyChar() + "").equals("D")
                || (evt.getKeyChar() + "").equals("F")
                || (evt.getKeyChar() + "").equals("G")
                || (evt.getKeyChar() + "").equals("H")
                || (evt.getKeyChar() + "").equals("J")
                || (evt.getKeyChar() + "").equals("K")
                || (evt.getKeyChar() + "").equals("L")
                || (evt.getKeyChar() + "").equals("Ñ")
                || (evt.getKeyChar() + "").equals("Z")
                || (evt.getKeyChar() + "").equals("X")
                || (evt.getKeyChar() + "").equals("C")
                || (evt.getKeyChar() + "").equals("V")
                || (evt.getKeyChar() + "").equals("B")
                || (evt.getKeyChar() + "").equals("N")
                || (evt.getKeyChar() + "").equals("M")
                || (evt.getKeyChar() + "").equals(" ")
                || (evt.getKeyChar() + "").equals("i")) || this.nombretext.getText().length() > 25) {
            evt.consume();
        }
    }//GEN-LAST:event_nombretextKeyTyped

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");

                    break;
                }

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombretext;
    // End of variables declaration//GEN-END:variables
}
